@startuml Ejercicio f
class Equipo
{
    Nombre: String
    Registro: String
}
class Jugador
{
    Número: Int
    Posición: String
    Capitán: Boolean
    Teléfono: String
    Nombre: String
    Dirección: String 
}
class Entrenador
{
    NivelAcreditación: String
    AñosExperiencia: Int
    Teléfono: String
    Nombre: String
    Dirección: String  
}
class Juego
{
    Localidad: String
    Puntuación: String
}

Equipo "1 " o-- "6..20"Jugador :tiene
Equipo "0..*" o-- "0..1 "Entrenador :entrena
Juego *-- "2" Equipo

object "E1:Entredaor1" as e1
e1 : NivelAcreditación= Internacional
e1 : AñosExperiencia = 10 
e1 : Teléfono= 0414-1234567
e1 : Nombre= Luis
e1 : Dirección= Maracay

object "Eq1:Equipo1" as eq1
eq1 : Nombre = Venezuela
eq1 : Registro = VEN123


object "Eq2:Equipo2" as eq2
eq2 : Nombre = Colombia
eq2 : Registro = COL456


object "J1:Jugador1" as j1
j1 : Número = 9
j1 : Nombre = Andrés
j1 : Posición = Libero
j1 : Capitán = true
j1 : Télefono = 0412-1234567
j1 : Dirección = Dirección

object "J2:Jugador2" as j2
j2 : Número = 3
j2 : Nombre = Luis
j2 : Posición = Atacante
j2 : Capitán = true
j2 : Télefono = 0412-1238562
j2 : Dirección = Dirección

object "J1:Jugador1" as j3
j3 : Número = 4
j3 : Nombre = Andrés
j3 : Posición = Atacante
j3 : Capitán = true
j3 : Télefono = 0312-7654321
j3 : Dirección = Bogotá
object "J2:Jugador2" as j4
j4 : Número = 5
j4 : Nombre = Juan
j4 : Posición = Libero
j4 : Capitán = true
j4 : Télefono = 0312-7654123
j4 : Dirección = Bogotá


object "Je:Juego" as je
je : Localidad = Santiago de Chile
je : Puntuación = Venezuela 3 - Colombia 2


eq1 o-- j1
eq1 o-- j2
eq1 o-- e1
eq2 o-- j3
eq2 o-- j4
je *-- eq1
je *-- eq2





@enduml