@startuml Ejercicio d

object "E1:Expreción" as o1
o1 : operadorBinario = /

object "E2:Expreción" as o2
o2 : operadorBinario = +

object "E3:Expreción" as o3
o3 : operadorBinario = +

object "E4:Expreción" as o4
o4 : operadorBinario = /

object "E5:Expreción" as o5
o5 : operadorBinario = /

object "V1:variable" as v1
v1 : nombre = x

object "V2:variable" as v2
v2 : nombre = y

object "C1:variable" as c1
c1 : valor = 2

object "C2:variable" as c2
c2 : valor = 4

	o1 o-- o2
    o1 o-- o3
    o2 o-- o4
    o2 o-- v1
    o4 o-- v2
    o4 o-- c1
    o5 o-- c2
    o3 o-- o5
    o3 o-- v2
    o5 o-- v1




@enduml
